server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/etl-countries
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true